Api end points
KitungaMP/K-api pull request #19
Opened 2020-12-02 19:26 UTC by bvenceslas

2020-12-02 22:48 UTC, guillainbisimwa requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello Josh :wave:

__You've made excellent progress with nice implementation of models and API :+1: 
However, some changes are required before it can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

_I hope all the `dates` will be automatically added _

* * *
**Please make the required changes and submit another review request when you are done.**

* * *

Gbisimwa

2020-12-02 22:48 UTC, guillainbisimwa commented on routes/api.js
> +    const {montant, somme, type, date, uid_sender, uid_receiver} = req.body;
'Montant` and `somme`?

2020-12-02 22:48 UTC, guillainbisimwa commented on routes/api.js
>  router.post('/register', (req, res) => {
Imaginer dans `register` on pas prevus bcp de details comme 

- [ ]  url profile
- [ ]  Adresse de livraison par defaut
- [ ] sex
A la longue on va ajouter ces elements dans l'app mais ne seront pas obligatoires

2020-12-03 04:56 UTC, bvenceslas commented on routes/api.js
>  router.post('/register', (req, res) => {
done, only verifier url_profile kama njo vile inapashwa kuwa

2020-12-03 04:57 UTC, bvenceslas commented on routes/api.js
> +    const {montant, somme, type, date, uid_sender, uid_receiver} = req.body;
j'ai enlevé la somme

2020-12-03 07:20 UTC, bvenceslas commented
![img_documents](https://user-images.githubusercontent.com/59555731/100976831-c1300800-3548-11eb-9497-d1672e4f6854.png)

2020-12-03 09:23 UTC, guillainbisimwa approved these changes
# Status:  APPROVED  🎉 🚀
#### :clap: :clap:
#### Don't forget to merge and deploy to Heroku! 

gbisimwa

2020-12-03 09:26 UTC, merged